/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import Ventas.VentaProductos;
import config.Utilidades;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author sergi
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPanelControl
     */
// Crear panel de fondo con imagen específica para el Formulario 1
    Utilidades fondo = new Utilidades("/imagenes/pass.png");
    String usuario;
    String rol;

    public FormularioPrincipal(String rol,String usuario) {
        this.setContentPane(fondo);

        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(720, 560);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  // Asegúrate de que se cierre todo al salir
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/login.png")).getImage());
       // Mostrar el nombre del usuario en un JLabel u otro componente asignamos rol a variable
       this.usuario=usuario;
       this.rol=rol;
       setTitle( "Bienvenido " + this.rol+": "+this.usuario+ "!");
       this.setResizable(false);

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jinventario = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jregistrarVenta = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Inventario");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jinventario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jinventario.setText("Productos");
        jinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinventarioActionPerformed(evt);
            }
        });
        jMenu4.add(jinventario);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("Ventas");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jregistrarVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jregistrarVenta.setText("Registrar venta");
        jregistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jregistrarVentaActionPerformed(evt);
            }
        });
        jMenu7.add(jregistrarVenta);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jregistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jregistrarVentaActionPerformed
    VentaProductos venta = new VentaProductos(this,rol,usuario);
    this.setVisible(false);
    venta.setVisible(true);
    venta.setLocationRelativeTo(null);        
    }//GEN-LAST:event_jregistrarVentaActionPerformed

    private void jinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinventarioActionPerformed
    
    FormularioInventario inventario = new FormularioInventario(this, rol,usuario);
    this.setVisible(false);
    inventario.setVisible(true);
    inventario.setLocationRelativeTo(null);        
    }//GEN-LAST:event_jinventarioActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JMenuItem jinventario;
    private javax.swing.JMenuItem jregistrarVenta;
    // End of variables declaration//GEN-END:variables
}
